// FrontendDevelopment_HandsOn/HandsOn_6/src/components/Header.jsx
import { Link } from 'react-router-dom';
import { useContext } from 'react'; // Import useContext
import { EnrollmentContext } from '../EnrollmentContext'; // Import our specific context

function Header({ siteName }) {
  // Grab the array directly from Context!
  const { enrolledCourses } = useContext(EnrollmentContext);

  return (
    <header style={{ backgroundColor: '#2c3e50', color: 'white', padding: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
      <h2>{siteName}</h2>
      <nav>
        <ul style={{ display: 'flex', gap: '15px', listStyle: 'none', padding: 0, margin: 0, alignItems: 'center' }}>
          <li><Link to="/" style={{ color: 'white', textDecoration: 'none', fontWeight: '500' }}>Home</Link></li>
          <li><Link to="/courses" style={{ color: 'white', textDecoration: 'none', fontWeight: '500' }}>Courses</Link></li>
          <li><Link to="/profile" style={{ color: 'white', textDecoration: 'none', fontWeight: '500' }}>Profile</Link></li>
          
          <li style={{ backgroundColor: '#1abc9c', padding: '5px 10px', borderRadius: '5px', fontWeight: 'bold', marginLeft: '10px' }}>
            {/* Display the length of the array! */}
            Enrolled: {enrolledCourses.length}
          </li>
        </ul>
      </nav>
    </header>
  );
}

export default Header;

// HandsOn_8/HandsOn_08/src/components/Header.vue
<script setup>
import { RouterLink } from 'vue-router'
import { useEnrollmentStore } from '../stores/enrollment'

// Access the Pinia store
const store = useEnrollmentStore()
</script>

<template>
  <header style="background-color: #2c3e50; padding: 20px; display: flex; justify-content: space-between; align-items: center;">
    <h2 style="color: white; margin: 0;">Vue Portal</h2>
    <nav style="display: flex; gap: 20px; align-items: center;">
      <RouterLink to="/" style="color: white; text-decoration: none; font-weight: bold;">Home</RouterLink>
      <RouterLink to="/courses" style="color: white; text-decoration: none; font-weight: bold;">Courses</RouterLink>
      <RouterLink to="/profile" style="color: white; text-decoration: none; font-weight: bold;">
        Profile 
        <!-- Dynamic Count Badge -->
        <span v-if="store.enrolledCourses.length > 0" style="background-color: #1abc9c; color: white; padding: 2px 8px; border-radius: 12px; font-size: 12px; margin-left: 5px;">
          {{ store.enrolledCourses.length }}
        </span>
      </RouterLink>
    </nav>
  </header>
</template>

<style scoped>
.router-link-active {
  color: #1abc9c !important; 
}
</style>
